[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tech-hiring-signals"
version = "0.1.0"
description = "ELT pipeline"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.34.2",
    "snowflake-connector-python>=4.8.0",
    "python-dotenv>=1.2.4",
    "dbt-snowflake>=1.12.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.10",
    "responses",
    "pre-commit"
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 88
target-version = "py310"
extend-exclude = ["airflow/.astro"]
force-exclude = true

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]