services:
  scheduler:
    volumes:
      - ../src:/usr/local/airflow/src:ro
      - ../dbt_tech_hiring:/usr/local/airflow/dbt_tech_hiring:ro
  dag-processor:
    volumes:
      - ../src:/usr/local/airflow/src:ro
      - ../dbt_tech_hiring:/usr/local/airflow/dbt_tech_hiring:ro
  triggerer:
    volumes:
      - ../src:/usr/local/airflow/src:ro
      - ../dbt_tech_hiring:/usr/local/airflow/dbt_tech_hiring:ro