services:
  scheduler:
    volumes:
      - ../src:/usr/local/airflow/src:ro
  dag-processor:
    volumes:
      - ../src:/usr/local/airflow/src:ro
  triggerer:
    volumes:
      - ../src:/usr/local/airflow/src:ro